[package]
name = "trying-proj"
description = "an attempt to make a basic video editor"
version = "0.1.0"
edition = "2021"

[dependencies]
# GUI library
gtk = { version = "0.4.1", package = "gtk4" }
# OpenGL backend
glium = "0.31.0"
libloading = "0.7.3"
epoxy = "0.1.0"
